export const theme = {
  colors: {
    background: 'var(--color-background)',
    card: 'var(--color-card)',
    border: 'var(--color-border)',
    accent: 'var(--color-accent)',
    text: {
      main: 'var(--color-text-main)',
      sub: 'var(--color-text-sub)',
      blur: 'var(--color-text-blur)',
    },
    tag: 'var(--color-tag)',
  },
  spacing: {
    xs: 'var(--spacing-xs)',
    sm: 'var(--spacing-sm)',
    md: 'var(--spacing-md)',
    lg: 'var(--spacing-lg)',
    xl: 'var(--spacing-xl)',
    '2xl': 'var(--spacing-2xl)',
  },
  layout: {
    cardWidth: 'var(--spacing-card-width)',
    cardSpacing: 'var(--spacing-card-gap)',
    cardRound: 'var(--radius-card)',
    imageRatio: 4 / 3,
    sidebarWidth: 'var(--spacing-sidebar)',
    gridColumn: 3,
  },
  font: {
    display: 'var(--font-display)',
    body: 'var(--font-body)',
  },
  style: {
    display: {
      fontFamily: 'var(--font-display)',
      fontSize: 'var(--text-display)',
      fontWeight: 700,
      letterSpacing: '-1px',
      lineHeight: 1.2,
    },
    headingLg: {
      fontFamily: 'var(--font-display)',
      fontSize: 'var(--text-heading-lg)',
      fontWeight: 700,
      letterSpacing: '-0.5px',
      lineHeight: 1.3,
    },
    headingSm: {
      fontFamily: 'var(--font-display)',
      fontSize: 'var(--text-heading-sm)',
      fontWeight: 700,
      letterSpacing: '-0.3px',
      lineHeight: 1.4,
    },
    body: {
      fontFamily: 'var(--font-body)',
      fontSize: 'var(--text-body)',
      fontWeight: 400,
      letterSpacing: 0,
      lineHeight: 1.6,
    },
    bodySm: {
      fontFamily: 'var(--font-body)',
      fontSize: 'var(--text-body-sm)',
      fontWeight: 400,
      letterSpacing: 0,
      lineHeight: 1.5,
    },
    label: {
      fontFamily: 'var(--font-display)',
      fontSize: 'var(--text-label)',
      fontWeight: 400,
      letterSpacing: '1.5px',
      lineHeight: 1.4,
      textTransform: 'uppercase' as const,
    },
    tag: {
      fontFamily: 'var(--font-display)',
      fontSize: 'var(--text-label)',
      fontWeight: 400,
      letterSpacing: '0.3px',
      lineHeight: 1,
    },
    price: {
      fontFamily: 'var(--font-display)',
      fontSize: 'var(--text-body-sm)',
      fontWeight: 700,
      letterSpacing: 0,
      lineHeight: 1,
    },
    button: {
      fontFamily: 'var(--font-body)',
      fontSize: 'var(--text-body-sm)',
      fontWeight: 600,
      letterSpacing: 0,
      lineHeight: 1,
    },
    nav: {
      fontFamily: 'var(--font-body)',
      fontSize: 'var(--text-body-sm)',
      fontWeight: 400,
      letterSpacing: 0,
      lineHeight: 1,
    },
  },
} as const